"""PDF report generator for ScholAR - Working version."""

from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_JUSTIFY, TA_CENTER
from reportlab.lib import colors


def generate_pdf_from_markdown(markdown_text: str) -> bytes:
    """
    Generate a professional PDF directly from markdown text.
    Ensures ALL content is included in the PDF.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    story = []
    styles = getSampleStyleSheet()

    # Define custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0066cc'),
        spaceAfter=20,
        spaceBefore=10,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    h2_style = ParagraphStyle(
        'CustomH2',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#003d99'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )

    h3_style = ParagraphStyle(
        'CustomH3',
        parent=styles['Heading3'],
        fontSize=13,
        textColor=colors.HexColor('#333333'),
        spaceAfter=10,
        spaceBefore=8,
        fontName='Helvetica-Bold'
    )

    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_JUSTIFY,
        spaceAfter=12,
        leading=16
    )

    list_style = ParagraphStyle(
        'CustomList',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_LEFT,
        spaceAfter=8,
        leading=14,
        leftIndent=20
    )

    # Add title
    story.append(Paragraph("Literature Review Report", title_style))
    story.append(Paragraph("Generated by ScholAR - Autonomous Research Agent", body_style))
    story.append(Spacer(1, 0.3*inch))

    # Parse and add all content from markdown
    lines = markdown_text.split('\n')

    for line in lines:
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 0.1*inch))
            continue

        try:
            # H1 headings
            if stripped.startswith('# '):
                text = stripped[2:].strip()
                if text:
                    story.append(Paragraph(text, title_style))
                    story.append(Spacer(1, 0.15*inch))

            # H2 headings
            elif stripped.startswith('## '):
                text = stripped[3:].strip()
                if text:
                    story.append(Paragraph(text, h2_style))
                    story.append(Spacer(1, 0.1*inch))

            # H3 headings
            elif stripped.startswith('### '):
                text = stripped[4:].strip()
                if text:
                    story.append(Paragraph(text, h3_style))
                    story.append(Spacer(1, 0.05*inch))

            # Bullet points
            elif stripped.startswith('- '):
                text = stripped[2:].strip()
                if text:
                    story.append(Paragraph(f"• {text}", list_style))

            # Bold text
            elif stripped.startswith('**') and stripped.endswith('**'):
                text = stripped[2:-2].strip()
                if text:
                    story.append(Paragraph(f"<b>{text}</b>", body_style))

            # Regular paragraphs
            else:
                if len(stripped) > 0:
                    story.append(Paragraph(stripped, body_style))

        except Exception as e:
            # Continue with other content if one line fails
            try:
                story.append(Paragraph(stripped, body_style))
            except:
                pass

    # Add footer
    story.append(Spacer(1, 0.3*inch))
    footer_text = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#999999'),
        alignment=TA_CENTER
    )
    story.append(Paragraph("Generated by ScholAR | Autonomous Research Discovery", footer_text))

    # Build PDF - THIS IS KEY - must call build()
    try:
        doc.build(story)
        buffer.seek(0)
        pdf_data = buffer.getvalue()

        if len(pdf_data) > 100:  # Check if PDF has content
            return pdf_data
        else:
            raise Exception("Generated PDF is too small")

    except Exception as e:
        print(f"PDF build error: {e}")
        raise


def generate_report_bytes(markdown_text: str, format_type: str = "pdf") -> tuple:
    """
    Generate report - ONLY PDF format supported.
    Returns: (bytes, file_extension, mime_type)
    """
    if format_type.lower() == "pdf":
        try:
            pdf_bytes = generate_pdf_from_markdown(markdown_text)
            return pdf_bytes, "pdf", "application/pdf"
        except Exception as e:
            print(f"PDF generation failed: {e}")
            raise
    else:
        raise ValueError("Only PDF format is supported")

